# Generated by Django 5.1.5 on 2025-02-05 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("class_attendance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="secret",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
