# Generated by Django 5.1.6 on 2025-02-06 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("class_attendance", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="name",
        ),
        migrations.AddField(
            model_name="student",
            name="first_name",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="student",
            name="last_name",
            field=models.CharField(default="", max_length=10),
            preserve_default=False,
        ),
    ]
